version: '3'
services:
  netflix :
    image: naveen070289/netflixrepo:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  aha:
    image: naveen070289/aharepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  hotstar:
    image: naveen070289/hotstarrepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  prime:
    image: naveen070289/primerepo:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
